name: ci

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          working-directory: ./packages/e2e-tests
