name: ci

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      - name: Install dependencies
        run: npm ci

      - name: Run Test
        run: npm run test
